# Generated by Django 2.1.2 on 2018-11-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
